namespace TiendaPe.Api;

public sealed record ProductRequest(
    string Name,
    string? Category,
    string? InternalCode,
    string? Barcode,
    string? Brand,
    string? Presentation,
    string? Unit,
    string? Supplier,
    decimal PurchasePrice,
    decimal SalePrice,
    decimal? WholesalePrice,
    int Stock,
    int MinimumStock,
    DateTime? ExpirationDate,
    string? Location,
    string? Notes,
    string? BaseUnit = null,
    string? TrackingType = null,
    decimal? ProfitMarginPercent = null,
    decimal? SuggestedPrice = null,
    string? PurchaseUnit = null,
    string? SaleUnit = null,
    decimal? UnitsPerPackage = null,
    DateTime? EntryDate = null,
    Guid? SupplierId = null,
    decimal? StockBase = null,
    decimal? MinimumStockBase = null,
    decimal? AverageCostBase = null,
    IReadOnlyList<ProductPresentationRequest>? Presentations = null);

public sealed record ProductPresentationRequest(
    Guid? Id,
    string Name,
    string? UnitLabel,
    decimal QuantityInBaseUnit,
    bool PurchaseEnabled,
    bool SaleEnabled,
    string? Barcode,
    decimal? PurchaseCost,
    decimal? SalePrice,
    decimal? WholesalePrice,
    decimal? SuggestedPrice,
    decimal? ProfitMarginPercent,
    bool IsDefaultPurchase,
    bool IsDefaultSale);

public sealed record ProductResponse(
    Guid Id,
    string Name,
    string Category,
    string? InternalCode,
    string? Barcode,
    string? Brand,
    string? Presentation,
    string? Unit,
    string? Supplier,
    decimal PurchasePrice,
    decimal SalePrice,
    decimal? WholesalePrice,
    int Stock,
    int MinimumStock,
    DateTime? ExpirationDate,
    string? Location,
    string? Notes,
    bool IsActive,
    bool IsLowStock,
    string BaseUnit,
    string TrackingType,
    decimal? ProfitMarginPercent,
    decimal? SuggestedPrice,
    string? PurchaseUnit,
    string? SaleUnit,
    decimal UnitsPerPackage,
    DateTime? EntryDate,
    Guid? SupplierId,
    decimal StockBase,
    decimal MinimumStockBase,
    decimal AverageCostBase,
    IReadOnlyList<ProductPresentationResponse> Presentations);

public sealed record ProductPresentationResponse(
    Guid Id,
    string Name,
    string UnitLabel,
    decimal QuantityInBaseUnit,
    bool PurchaseEnabled,
    bool SaleEnabled,
    string? Barcode,
    decimal? PurchaseCost,
    decimal? SalePrice,
    decimal? WholesalePrice,
    decimal? SuggestedPrice,
    decimal? ProfitMarginPercent,
    bool IsDefaultPurchase,
    bool IsDefaultSale,
    bool IsActive);
